module GDFunc.CodeGenSpec (spec) where

import Test.Hspec
import GDFunc.CodeGen
import GDFunc.Parser
import Data.List (isInfixOf, isPrefixOf)

-- Helper to create a simple module
makeModule :: String -> [Declaration] -> Module
makeModule name decls = Module [name] Nothing [] decls

-- Helper to check if generated code contains a substring
codeContains :: String -> String -> Expectation
codeContains haystack needle =
    if needle `isInfixOf` haystack
        then True `shouldBe` True
        else expectationFailure $
            "Expected code to contain: " ++ show needle ++
            "\nBut got:\n" ++ haystack

-- Helper to check if generated code starts with a prefix
codeStartsWith :: String -> String -> Expectation
codeStartsWith str prefix =
    if prefix `isPrefixOf` str
        then True `shouldBe` True
        else expectationFailure $
            "Expected to start with: " ++ show prefix ++
            "\nBut got:\n" ++ take 100 str

spec :: Spec
spec = do
    describe "Code Generation" $ do
        describe "Module Structure" $ do
            it "generates C header comments" $ do
                let mod = makeModule "Test" []
                let code = generateC mod
                code `shouldContain` "// Generated by GDFunc compiler"

            it "includes standard C headers" $ do
                let mod = makeModule "Test" []
                let code = generateC mod
                code `shouldContain` "#include <stdio.h>"
                code `shouldContain` "#include <stdlib.h>"
                code `shouldContain` "#include <string.h>"
                code `shouldContain` "#include <stdint.h>"

            it "generates main entry point" $ do
                let mod = makeModule "Test" []
                let code = generateC mod
                code `shouldContain` "int main(int argc, char** argv)"

        describe "Runtime Support" $ do
            it "generates List structure definition" $ do
                let mod = makeModule "Test" []
                let code = generateC mod
                code `shouldContain` "typedef struct List"
                code `shouldContain` "void* head;"
                code `shouldContain` "struct List* tail;"
                code `shouldContain` "int is_nil;"

            it "generates nil constructor" $ do
                let mod = makeModule "Test" []
                let code = generateC mod
                code `shouldContain` "List* nil()"
                code `shouldContain` "l->is_nil = 1;"

            it "generates cons constructor" $ do
                let mod = makeModule "Test" []
                let code = generateC mod
                code `shouldContain` "List* cons(void* head, List* tail)"
                code `shouldContain` "l->head = head;"
                code `shouldContain` "l->tail = tail;"

            it "generates linear resource tracking placeholder" $ do
                let mod = makeModule "Test" []
                let code = generateC mod
                code `shouldContain` "void consume_linear(void* ptr)"

        describe "Function Declarations" $ do
            it "generates simple function with no arguments" $ do
                let decl = FunctionDecl "getValue" [] (EInt 42)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "int getValue()"
                code `shouldContain` "return 42;"

            it "generates function with one argument" $ do
                let decl = FunctionDecl "identity" [PVar "x"] (EVar "x")
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "int identity(int arg0)"

            it "generates function with multiple arguments" $ do
                let decl = FunctionDecl "add"
                        [PVar "a", PVar "b"]
                        (EBinOp "+" (EVar "a") (EVar "b"))
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "int add(int arg0, int arg1)"

            it "sanitizes function names with special characters" $ do
                let decl = FunctionDecl "my-func" [] (EInt 1)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "int my_func"

            it "generates forward declarations" $ do
                let decl = FunctionDecl "factorial" [PVar "n"] (EInt 1)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "// Forward declarations"
                code `shouldContain` "int factorial(int arg0);"

        describe "Expression Generation" $ do
            it "generates integer literals" $ do
                let decl = FunctionDecl "test" [] (EInt 42)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "return 42;"

            it "generates float literals" $ do
                let decl = FunctionDecl "test" [] (EFloat 3.14)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "return 3.14;"

            it "generates variable references" $ do
                let decl = FunctionDecl "identity" [PVar "x"] (EVar "x")
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "return arg0;"

            it "generates binary operations" $ do
                let expr = EBinOp "+" (EInt 2) (EInt 3)
                let decl = FunctionDecl "test" [] expr
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "2 + 3"

            it "generates if expressions" $ do
                let expr = EIf (EVar "x") (EInt 1) (EInt 0)
                let decl = FunctionDecl "test" [PVar "x"] expr
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "if"
                code `shouldContain` "else"

            it "generates function applications" $ do
                let expr = EApp (EVar "f") (EInt 5)
                let decl = FunctionDecl "test" [PVar "f"] expr
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                -- Should generate a function call
                -- The exact format depends on implementation
                True `shouldBe` True  -- Placeholder

        describe "Type Annotations" $ do
            it "generates type annotations as comments" $ do
                let annot = TypeAnnotation "factorial"
                        (TArrow (TCon "Int" []) (TCon "Int" []))
                let mod = makeModule "Test" [annot]
                let code = generateC mod
                code `shouldContain` "// factorial :"

        describe "Pattern Matching" $ do
            it "binds variable patterns to parameters" $ do
                let decl = FunctionDecl "test" [PVar "x", PVar "y"] (EVar "x")
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "int arg0"
                code `shouldContain` "int arg1"

            it "handles borrowed patterns" $ do
                let decl = FunctionDecl "test" [PBorrow (PVar "list")] (EInt 0)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "// Borrowed parameter"

        describe "Main Function" $ do
            it "calls main function if it exists" $ do
                let mainDecl = FunctionDecl "main" [] (EInt 42)
                let mod = makeModule "Test" [mainDecl]
                let code = generateC mod
                code `shouldContain` "int result = main(0);"
                code `shouldContain` "printf(\"%d\\n\", result);"

            it "prints message if no main function exists" $ do
                let decl = FunctionDecl "other" [] (EInt 1)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "printf(\"No main function defined\\n\");"

        describe "Complete Examples" $ do
            it "generates code for factorial function" $ do
                let typeAnnot = TypeAnnotation "factorial"
                        (TArrow (TCon "Int" []) (TCon "Int" []))
                let funcDecl = FunctionDecl "factorial" [PVar "n"]
                        (EIf
                            (EBinOp "<=" (EVar "n") (EInt 1))
                            (EInt 1)
                            (EBinOp "*"
                                (EVar "n")
                                (EApp (EVar "factorial")
                                    (EBinOp "-" (EVar "n") (EInt 1)))))
                let mod = makeModule "Factorial" [typeAnnot, funcDecl]
                let code = generateC mod

                -- Check structure
                code `shouldContain` "int factorial(int arg0)"
                code `shouldContain` "if"
                code `shouldContain` "else"

            it "generates code for identity function" $ do
                let decl = FunctionDecl "identity" [PVar "x"] (EVar "x")
                let mainDecl = FunctionDecl "main" []
                        (EApp (EVar "identity") (EInt 42))
                let mod = makeModule "Identity" [decl, mainDecl]
                let code = generateC mod

                code `shouldContain` "int identity(int arg0)"
                code `shouldContain` "int main()"

            it "generates code for const function" $ do
                let decl = FunctionDecl "const" [PVar "x", PVar "y"] (EVar "x")
                let mod = makeModule "Const" [decl]
                let code = generateC mod

                code `shouldContain` "int const(int arg0, int arg1)"
                code `shouldContain` "return arg0;"

        describe "Name Sanitization" $ do
            it "sanitizes hyphens to underscores" $ do
                let decl = FunctionDecl "my-function" [] (EInt 1)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "my_function"

            it "sanitizes prime marks" $ do
                let decl = FunctionDecl "x'" [] (EInt 1)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                code `shouldContain` "x_"

            it "handles empty names gracefully" $ do
                -- Edge case: if somehow an empty name gets through
                let decl = FunctionDecl "" [] (EInt 1)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                -- Should not crash, sanitizeName should handle it
                code `shouldContain` "#include"

        describe "Code Organization" $ do
            it "generates sections in correct order" $ do
                let decl = FunctionDecl "test" [] (EInt 1)
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                let codeLines = lines code

                -- Headers should come first
                let headerIdx = head [i | (i, l) <- zip [0..] codeLines, "#include" `isInfixOf` l]
                -- Runtime support should come after headers
                let runtimeIdx = head [i | (i, l) <- zip [0..] codeLines, "// Runtime support" `isInfixOf` l]
                -- Forward declarations should come after runtime
                let forwardIdx = head [i | (i, l) <- zip [0..] codeLines, "// Forward declarations" `isInfixOf` l]

                headerIdx `shouldSatisfy` (< runtimeIdx)
                runtimeIdx `shouldSatisfy` (< forwardIdx)

        describe "Edge Cases" $ do
            it "handles module with no declarations" $ do
                let mod = makeModule "Empty" []
                let code = generateC mod
                code `shouldContain` "// Generated by GDFunc compiler"
                code `shouldContain` "int main(int argc, char** argv)"

            it "handles nested binary operations" $ do
                let expr = EBinOp "+"
                        (EBinOp "*" (EInt 2) (EInt 3))
                        (EBinOp "/" (EInt 10) (EInt 2))
                let decl = FunctionDecl "test" [] expr
                let mod = makeModule "Test" [decl]
                let code = generateC mod
                -- Should generate valid C code with proper precedence
                code `shouldContain` "int test()"

            it "handles multiple functions in one module" $ do
                let decl1 = FunctionDecl "add" [PVar "a", PVar "b"]
                        (EBinOp "+" (EVar "a") (EVar "b"))
                let decl2 = FunctionDecl "sub" [PVar "a", PVar "b"]
                        (EBinOp "-" (EVar "a") (EVar "b"))
                let decl3 = FunctionDecl "main" []
                        (EApp (EApp (EVar "add") (EInt 5)) (EInt 3))
                let mod = makeModule "Math" [decl1, decl2, decl3]
                let code = generateC mod

                code `shouldContain` "int add(int arg0, int arg1)"
                code `shouldContain` "int sub(int arg0, int arg1)"
                code `shouldContain` "int main()"
