{-# LANGUAGE OverloadedStrings #-}

module GDFunc.IntegrationSpec (spec) where

import Test.Hspec
import GDFunc.Scanner
import GDFunc.Parser
import GDFunc.CodeGen
import System.FilePath ((</>), takeBaseName)
import System.Directory (doesFileExist, listDirectory, getCurrentDirectory)
import Control.Exception (try, SomeException)
import Data.List (isSuffixOf, isInfixOf)

-- Helper to read and compile a .gdfunc file
compileFile :: FilePath -> IO (Either String String)
compileFile path = do
    exists <- doesFileExist path
    if not exists
        then return $ Left $ "File not found: " ++ path
        else do
            result <- try (readFile path) :: IO (Either SomeException String)
            case result of
                Left err -> return $ Left $ "Error reading file: " ++ show err
                Right source -> return $ compilePipeline source

-- Full compilation pipeline
compilePipeline :: String -> Either String String
compilePipeline source = do
    -- Step 1: Scan
    tokens <- case scanTokens source of
        Left err -> Left $ "Scan error: " ++ show err
        Right ts -> Right ts

    -- Step 2: Parse
    let filteredTokens = filter (not . isComment) tokens
    mod <- case parseModule filteredTokens of
        Left err -> Left $ "Parse error: " ++ show err
        Right m -> Right m

    -- Step 3: Generate C code
    let cCode = generateC mod
    Right cCode
  where
    isComment tok = case tokenType tok of
        COMMENT _ -> True
        _ -> False

-- Helper to check if C code is valid (basic checks)
isValidCCode :: String -> Bool
isValidCCode code =
    all (`elem` requiredElements) requiredElements
  where
    requiredElements =
        [ "#include"
        , "int main"
        ]

spec :: Spec
spec = do
    describe "Integration Tests - Example Files" $ do
        describe "factorial.gdfunc" $ do
            let examplePath = "examples/factorial.gdfunc"

            it "exists and is readable" $ do
                exists <- doesFileExist examplePath
                exists `shouldBe` True

            it "scans successfully" $ do
                source <- readFile examplePath
                case scanTokens source of
                    Left err -> expectationFailure $ "Scan failed: " ++ show err
                    Right tokens -> length tokens `shouldSatisfy` (> 0)

            it "parses successfully" $ do
                source <- readFile examplePath
                case scanTokens source of
                    Left err -> expectationFailure $ "Scan failed: " ++ show err
                    Right tokens -> do
                        let filtered = filter (\t -> case tokenType t of
                                COMMENT _ -> False
                                _ -> True) tokens
                        case parseModule filtered of
                            Left err -> expectationFailure $ "Parse failed: " ++ show err
                            Right (Module name _ _ decls) -> do
                                name `shouldBe` ["Factorial"]
                                length decls `shouldSatisfy` (>= 2)

            it "generates C code" $ do
                result <- compileFile examplePath
                case result of
                    Left err -> expectationFailure err
                    Right cCode -> do
                        cCode `shouldContain` "#include"
                        cCode `shouldContain` "int main"
                        cCode `shouldContain` "factorial"

            it "generates valid C structure" $ do
                result <- compileFile examplePath
                case result of
                    Left err -> expectationFailure err
                    Right cCode -> do
                        cCode `shouldContain` "// Generated by GDFunc compiler"
                        cCode `shouldContain` "typedef struct List"
                        cCode `shouldContain` "int factorial"

        describe "borrowing_example.gdfunc" $ do
            let examplePath = "examples/borrowing_example.gdfunc"

            it "exists and is readable" $ do
                exists <- doesFileExist examplePath
                exists `shouldBe` True

            it "compiles successfully" $ do
                result <- compileFile examplePath
                case result of
                    Left err -> expectationFailure err
                    Right cCode -> cCode `shouldContain` "#include"

            it "handles borrowed references in generated code" $ do
                result <- compileFile examplePath
                case result of
                    Left err -> expectationFailure err
                    Right cCode -> do
                        -- Check for borrowed parameter comment or handling
                        cCode `shouldContain` "// Borrowed"

        describe "shared_types.gdfunc" $ do
            let examplePath = "examples/shared_types.gdfunc"

            it "exists and is readable" $ do
                exists <- doesFileExist examplePath
                exists `shouldBe` True

            it "compiles successfully" $ do
                result <- compileFile examplePath
                case result of
                    Left err -> expectationFailure err
                    Right cCode -> cCode `shouldContain` "#include"

            it "handles shared type declarations" $ do
                result <- compileFile examplePath
                case result of
                    Left err -> expectationFailure err
                    Right cCode -> do
                        -- Shared types should appear as comments
                        cCode `shouldContain` "// type shared"

        describe "linear_default.gdfunc" $ do
            let examplePath = "examples/linear_default.gdfunc"

            it "exists and is readable" $ do
                exists <- doesFileExist examplePath
                exists `shouldBe` True

            it "compiles successfully" $ do
                result <- compileFile examplePath
                case result of
                    Left err -> expectationFailure err
                    Right cCode -> cCode `shouldContain` "#include"

        describe "quicksort_linear.gdfunc" $ do
            let examplePath = "examples/quicksort_linear.gdfunc"

            it "exists and is readable" $ do
                exists <- doesFileExist examplePath
                exists `shouldBe` True

            it "compiles successfully" $ do
                result <- compileFile examplePath
                case result of
                    Left err -> expectationFailure err
                    Right cCode -> cCode `shouldContain` "#include"

        describe "All Examples - End-to-End" $ do
            it "all example files compile to C code" $ do
                cwd <- getCurrentDirectory
                let examplesDir = "examples"
                exists <- doesFileExist examplesDir

                if exists
                    then do
                        files <- listDirectory examplesDir
                        let gdfuncFiles = filter (isSuffixOf ".gdfunc") files
                        let examplePaths = map (examplesDir </>) gdfuncFiles

                        forM_ examplePaths $ \path -> do
                            result <- compileFile path
                            case result of
                                Left err -> expectationFailure $
                                    "Failed to compile " ++ path ++ ": " ++ err
                                Right cCode -> do
                                    cCode `shouldContain` "#include"
                                    cCode `shouldContain` "int main"
                    else pendingWith "examples directory not found"

        describe "Compilation Pipeline" $ do
            it "reports meaningful error for invalid syntax" $ do
                let invalidSource = "this is not valid gdfunc code !!!"
                case compilePipeline invalidSource of
                    Left err -> err `shouldContain` "error"
                    Right _ -> expectationFailure "Should have failed on invalid syntax"

            it "reports error for incomplete module declaration" $ do
                let incompleteSource = "module Test"
                case compilePipeline incompleteSource of
                    Left err -> err `shouldContain` "error"
                    Right _ -> expectationFailure "Should have failed on incomplete module"

            it "handles empty module" $ do
                let emptyModule = unlines
                        [ "module Empty exposing (..)"
                        , ""
                        ]
                case compilePipeline emptyModule of
                    Left err -> expectationFailure $ "Should compile empty module: " ++ err
                    Right cCode -> do
                        cCode `shouldContain` "#include"
                        cCode `shouldContain` "int main"

        describe "Generated C Code Quality" $ do
            it "includes all necessary runtime support" $ do
                let simpleModule = unlines
                        [ "module Test exposing (main)"
                        , ""
                        , "main = 42"
                        ]
                case compilePipeline simpleModule of
                    Left err -> expectationFailure err
                    Right cCode -> do
                        -- Check for runtime structures
                        cCode `shouldContain` "typedef struct List"
                        cCode `shouldContain` "List* nil()"
                        cCode `shouldContain` "List* cons"
                        cCode `shouldContain` "void consume_linear"

            it "generates forward declarations for all functions" $ do
                let moduleWithMultipleFunctions = unlines
                        [ "module Test exposing (..)"
                        , ""
                        , "add : Int -> Int -> Int"
                        , "add a b = a + b"
                        , ""
                        , "multiply : Int -> Int -> Int"
                        , "multiply a b = a * b"
                        , ""
                        , "main = add 2 3"
                        ]
                case compilePipeline moduleWithMultipleFunctions of
                    Left err -> expectationFailure err
                    Right cCode -> do
                        cCode `shouldContain` "// Forward declarations"
                        cCode `shouldContain` "int add"
                        cCode `shouldContain` "int multiply"

            it "properly orders sections: headers -> runtime -> declarations -> main" $ do
                let testModule = unlines
                        [ "module Test exposing (main)"
                        , ""
                        , "helper = 10"
                        , "main = helper"
                        ]
                case compilePipeline testModule of
                    Left err -> expectationFailure err
                    Right cCode -> do
                        let codeLines = lines cCode
                        let indices =
                                [ (idx, marker)
                                | (idx, line) <- zip [0..] codeLines
                                , marker <- ["#include", "// Runtime", "// Forward", "int main(int argc"]
                                , marker `isInfixOf` line
                                ]
                        -- Headers should come before runtime, etc.
                        length indices `shouldSatisfy` (>= 3)

        describe "Error Handling" $ do
            it "provides helpful error for missing main function" $ do
                -- This should compile but note no main function
                let noMainModule = unlines
                        [ "module Test exposing (..)"
                        , ""
                        , "helper = 42"
                        ]
                case compilePipeline noMainModule of
                    Left err -> expectationFailure $ "Should compile: " ++ err
                    Right cCode ->
                        cCode `shouldContain` "No main function defined"

            it "handles lexical errors gracefully" $ do
                let badLexicalSource = "module Test\n\n@#$%^&*"
                case compilePipeline badLexicalSource of
                    Left err -> err `shouldContain` "error"
                    Right _ -> expectationFailure "Should fail on bad lexical input"

-- Helper for IO operations in tests
forM_ :: [a] -> (a -> IO ()) -> IO ()
forM_ = flip mapM_
