-- | GDScript backend.
--
-- The implementation here is a stub that emits a placeholder script
-- so the CLI surface and golden-test harness can wire '--target
-- gdscript' end-to-end. The real backend will arrive once
-- 'prettyprinter' replaces the string-mashed output and the parser
-- carries source spans through to the codegen layer.
module GDFunc.CodeGen.GDScript
    ( generateGDScript
    , compileToGDScriptFile
    ) where

import GDFunc.Parser (Module(..))

-- | Emit GDScript source for a module. Currently a placeholder; see
-- module docs.
generateGDScript :: Module -> String
generateGDScript m = unlines
    [ "# Generated by GDFunc (GDScript backend, stub)"
    , "# Source module: " ++ moduleNamePretty m
    , "#"
    , "# The GDScript backend is under construction. This stub keeps the"
    , "# CLI '--target gdscript' wiring compiling and gives golden tests"
    , "# something to lock onto until the real codegen lands."
    , ""
    , "extends Node"
    , ""
    , "func _ready() -> void:"
    , "\tpush_warning(\"GDFunc: GDScript backend not yet implemented\")"
    ]
  where
    moduleNamePretty (Module name _ _ _) = case name of
        []    -> "<anonymous>"
        parts -> joinDots parts
    joinDots []     = ""
    joinDots [p]    = p
    joinDots (p:ps) = p ++ "." ++ joinDots ps

-- | Write GDScript output to a file.
compileToGDScriptFile :: FilePath -> Module -> IO ()
compileToGDScriptFile path m = do
    writeFile path (generateGDScript m)
    putStrLn $ "Generated GDScript written to: " ++ path
